#ifndef ALARM_MODEL_H
#define ALARM_MODEL_H

#include <math.h>
#include <stdint.h>

// Generated by hasaki dev
// Architecture: 12-8-4-1
// Quantization: int8

// ===== INPUT NORMALIZATION METADATA =====
// Use these ranges to normalize inputs BEFORE calling predict()

// hasaki exported model

// Input ranges (min/max observed during training)
// NOTE: Normalize inputs BEFORE calling predict():
// for (int i = 0; i < NUM_INPUTS; i++)
//     input[i] = (raw_input[i] - INPUT_MIN[i]) / (INPUT_MAX[i] - INPUT_MIN[i]);
// predict(input, output);

static inline float sigmoid(float x)    { return 1.0f / (1.0f + expf(-x)); }
static inline float tanh_act(float x)   { return tanhf(x); }
static inline float relu(float x)        { return x > 0.0f ? x : 0.0f; }
static inline float leaky_relu(float x)  { return x > 0.0f ? x : 0.01f * x; }
static inline float linear(float x)      { return x; }
static inline float softmax(float x)     { return x; } // Identity: normalization at layer level

const int8_t w1[8][12] = {
    {17, -70, 124, -127, -23, -30, 42, -56, -62, -47, -63, -24},
    {1, 12, 127, -65, 8, -7, -6, 48, 41, 45, 38, 58},
    {23, 13, 127, -15, 16, 22, -1, 108, 78, 115, 84, -40},
    {11, 12, -127, -35, 2, -4, 15, -49, -36, -54, -34, 103},
    {25, -6, 127, 42, 3, -5, -7, -16, -27, -6, -33, -110},
    {0, 0, -43, -31, -1, -1, 0, -126, -123, -127, -124, -104},
    {-13, 13, 127, 65, 14, 9, 5, 1, -13, 7, -17, -81},
    {1, 0, 127, 96, 10, 13, -24, 47, 48, 47, 44, 98}
};
const float b1[8] = {1.77692, -0.784914, -1.17708, 1.78113, -0.00360594, 1.15749, 1.83574, 0.266209};
const float w1_scales[8] = {5.517990551e-02f, 1.119360630e-01f, 1.388551969e-01f, 1.646629134e-01f, 1.222430709e-01f, 7.485021260e-01f, 1.913579528e-01f, 8.125566929e-02f};

const int8_t w2[4][8] = {
    {2, -15, 2, -10, 18, -127, 14, -80},
    {0, -10, 14, -5, 10, -61, 7, -127},
    {-2, 33, 56, -18, -18, -37, -23, -127},
    {76, 97, -31, 56, -24, 127, -8, 17}
};
const float b2[4] = {-1.243399000e+00, -2.448892000e+00, -3.481846000e+00, 2.805954000e+00};
const float w2_scales[4] = {8.195834646e-02f, 1.722513386e-01f, 1.131643307e-01f, 6.523141732e-02f};

const int8_t w3[1][4] = {
    {119, 16, 127, -49}
};
const float b3[1] = {4.944137000e+00};
const float w3_scales[1] = {1.507648031e-01f};

static inline void predict_int8(const float* input, float* output) {
    float a[8], b[8];
    float logits[8];
    const float* in = input;
    float* out = a;

    // layer 1 (relu) - INT8 SYMMETRIC QUANTIZED
    for (int i = 0; i < 8; i++) {
        float dot_product = 0.0f;
        for (int j = 0; j < 12; j++) {
            dot_product += (float)w1[i][j] * in[j];
        }
        float sum = b1[i] + (dot_product * w1_scales[i]);
        out[i] = relu(sum);
    }
    in = out; out = (out == a) ? b : a;

    // layer 2 (relu) - INT8 SYMMETRIC QUANTIZED
    for (int i = 0; i < 4; i++) {
        float dot_product = 0.0f;
        for (int j = 0; j < 8; j++) {
            dot_product += (float)w2[i][j] * in[j];
        }
        float sum = b2[i] + (dot_product * w2_scales[i]);
        out[i] = relu(sum);
    }
    in = out; out = (out == a) ? b : a;

    // layer 3 (sigmoid) - INT8 SYMMETRIC QUANTIZED
    for (int i = 0; i < 1; i++) {
        float dot_product = 0.0f;
        for (int j = 0; j < 4; j++) {
            dot_product += (float)w3[i][j] * in[j];
        }
        float sum = b3[i] + (dot_product * w3_scales[i]);
        out[i] = sigmoid(sum);
    }

    for (int i = 0; i < 1; i++)
        output[i] = out[i];
}

// Wrapper: predict() delegates to predict_int8()
static inline void predict(const float* input, float* output) {
    predict_int8(input, output);
}

#endif // ALARM_MODEL_H
